version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - automated
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)
      include: scope

  - package-ecosystem: gomod
    directory: /apps/api
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    labels:
      - dependencies
      - automated
    commit-message:
      prefix: chore(deps-go)
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    labels:
      - dependencies
      - automated
    commit-message:
      prefix: ci(deps)
      include: scope

  - package-ecosystem: docker
    directory: /infra
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    labels:
      - dependencies
      - automated
    commit-message:
      prefix: chore(docker)
      include: scope
